name: time printer

on: push

jobs:
    printer:
        runs-on: ubuntu-latest
        steps:
          - name: time printer
            run: time -p
          - name: second printer
            run: date
          - name: third
            run: timedatectl

    validator:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/Checkout@V6
            - name: validator
              uses: Cyb3r-Jak3/html5validator-action
              with:
                root: ./