name: pipeline

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
    printer:
        runs-on: ubuntu-latest
        steps:
          - name: time printer
            run: time -p
          - name: second printer
            run: date
          - name: third
            run: timedatectl

    validator:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6.0.2
            - name: validator
              uses: Cyb3r-Jak3/html5validator-action@v7.2.0
              with:
                root: ./

    delopy:
        runs-on: ubuntu-latest
        steps:
            - name: check repo
              uses: actions/checkout@v2
            - name: Build image
              run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/test-website:latest .
            - name: login docker
              uses: docker/login-action@v4.2.0
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: push
              run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/test-website:latest
            - name: Deploy it to pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: .