name: time printer

on: push

jobs:
    printer:
        runs-on: ubuntu-latest
        steps:
          - name: time printer
            run: time -p
          - name: second printer
            run: date
          - name: third
            run: timedatectl